version: '3.9'

services:
  orchestrator:
    build:
      context: .
      dockerfile: services/orchestrator/Dockerfile
    environment:
      CAPSULE_URL: "http://capsule-demo:9000"
    volumes:
      - ./services/orchestrator:/app/orchestrator
      - ./config:/app/config
    command: uvicorn orchestrator.app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  capsule-demo:
    build:
      context: .
      dockerfile: services/capsule/Dockerfile
    environment:
      ADAPTER_ID: "defender-demo"
      ADAPTER_PATH: "/data/adapter"
    volumes:
      - ./services/capsule:/app/services/capsule  
      - ./data/capsules/defender-demo:/data/adapter
    command: uvicorn services.capsule.mcp_server:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
