services:
  inference:
    build:
      context: .
      dockerfile: inference/Dockerfile
    container_name: tessera-inference
    ports:
      - "8082:8082"

  orchestrator:
    build:
      context: .
      dockerfile: orchestrator/Dockerfile
    container_name: tessera-orchestrator
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    environment:
      - INFER_URL=http://inference:8082
    depends_on:
      - inference

  style-judge:
    build:
      context: .
      dockerfile: style-judge/Dockerfile
    container_name: tessera-style-judge
    ports:
      - "8091:8091"
