global:
  scrape_interval: 5s     
  evaluation_interval: 5s 

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8000']

  - job_name: 'capsule-demo'
    static_configs:
      - targets: ['capsule-demo:9000']
